In [12]:
import numpy as np

In [22]:
M = np.matrix(
    '0.04 0.24 0.24 0.24 0.24 0 0 0 0 0;' + 
    '0 0 0.1 0 0 0.55 0.35 0 0 0;'+
    '0 0 0 0 0 0.6 0.4 0 0 0;'+
    '0 0 0 0 0 0 0 0.6 0.4 0;'+
    '0 0 0 0.1 0 0 0 0.55 0.35 0;'+
    '0 0.25 0 0 0 0 0 0 0 0.75;' + 
    '0 0 0 0 0 0 0 0.05 0 0.95;' +
    '0 0 0 0 0 0 0.05 0 0 0.95;' +
    '0 0 0 0 0.25 0 0 0 0 0.75;'+
    '0 0 0 0 0 0 0 0 0 0'
)

In [23]:
from math import log2
E = []
for i in range(10):
    val = 0
    for j in range(10):
        if M[i,j] != 0:
            val += M[i,j] * log2(M[i,j])
    val = val * -1
    E.append([val])
    print(val)
E = np.matrix(E)

2.162292189082415
1.3366664819166874
0.9709505944546686
0.9709505944546686
1.3366664819166874
0.8112781244591328
0.28639695711595625
0.28639695711595625
0.8112781244591328
0


In [24]:
M = np.identity(10) - M
print(M)

[[ 0.96 -0.24 -0.24 -0.24 -0.24  0.    0.    0.    0.    0.  ]
 [ 0.    1.   -0.1   0.    0.   -0.55 -0.35  0.    0.    0.  ]
 [ 0.    0.    1.    0.    0.   -0.6  -0.4   0.    0.    0.  ]
 [ 0.    0.    0.    1.    0.    0.    0.   -0.6  -0.4   0.  ]
 [ 0.    0.    0.   -0.1   1.    0.    0.   -0.55 -0.35  0.  ]
 [ 0.   -0.25  0.    0.    0.    1.    0.    0.    0.   -0.75]
 [ 0.    0.    0.    0.    0.    0.    1.   -0.05  0.   -0.95]
 [ 0.    0.    0.    0.    0.    0.   -0.05  1.    0.   -0.95]
 [ 0.    0.    0.    0.   -0.25  0.    0.    0.    1.   -0.75]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    1.  ]]


In [25]:
np.linalg.det(M)

0.7324383149999999

In [26]:
M_1 = np.linalg.inv(M)

In [27]:
print(M_1)

[[1.04166667 0.33923304 0.2839233  0.28047091 0.30470914 0.35693215
  0.24971881 0.34835852 0.21883657 1.        ]
 [0.         1.179941   0.1179941  0.         0.         0.71976401
  0.46133032 0.02306652 0.         1.        ]
 [0.         0.17699115 1.01769912 0.         0.         0.7079646
  0.47020205 0.0235101  0.         1.        ]
 [0.         0.         0.         1.01108033 0.11080332 0.
  0.03346316 0.66926319 0.4432133  1.        ]
 [0.         0.         0.         0.11080332 1.10803324 0.
  0.03387971 0.67759426 0.43213296 1.        ]
 [0.         0.29498525 0.02949853 0.         0.         1.179941
  0.11533258 0.00576663 0.         1.        ]
 [0.         0.         0.         0.         0.         0.
  1.00250627 0.05012531 0.         1.        ]
 [0.         0.         0.         0.         0.         0.
  0.05012531 1.00250627 0.         1.        ]
 [0.         0.         0.         0.02770083 0.27700831 0.
  0.00846993 0.16939857 1.10803324 1.        ]
 [0.    

In [28]:
res = M_1.dot(E)

In [29]:
print(res)

[[4.29951862]
 [2.41441261]
 [1.94046755]
 [1.69064408]
 [2.14299945]
 [1.41488128]
 [0.30147048]
 [0.30147048]
 [1.34702799]
 [0.        ]]
