In [1]:
import numpy as np

In [2]:
M = np.matrix(
    '0.04 0.24 0.24 0.24 0.24 0 0 0 0 0;' + 
    '0 0 0.1 0 0 0.55 0.35 0 0 0;'+
    '0 0 0 0 0 0.6 0.4 0 0 0;'+
    '0 0 0 0 0 0 0 0.6 0.4 0;'+
    '0 0 0 0.1 0 0 0 0.55 0.35 0;'+
    '0 0.25 0 0 0 0 0 0 0 0.75;' + 
    '0 0 0 0 0 0 0 0.05 0 0.95;' +
    '0 0 0 0 0 0 0.05 0 0 0.95;' +
    '0 0 0 0 0.25 0 0 0 0 0.75;'+
    '0 0 0 0 0 0 0 0 0 0'
)

In [7]:
from math import log2
E = []
for i in range(10):
    val = 0
    for j in range(10):
        if M[i,j] != 0:
            val += M[i,j] * log2(M[i,j])
    val = val * -1
    E.append([val])
    print(val)
E = np.matrix(E)

2.162292189082415
1.3366664819166876
0.9709505944546686
0.9709505944546686
1.3366664819166876
0.8112781244591328
0.28639695711595625
0.28639695711595625
0.8112781244591328
0


In [8]:
M = np.ones((10,10)) - M
print(M)

[[0.96 0.76 0.76 0.76 0.76 1.   1.   1.   1.   1.  ]
 [1.   1.   0.9  1.   1.   0.45 0.65 1.   1.   1.  ]
 [1.   1.   1.   1.   1.   0.4  0.6  1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   0.4  0.6  1.  ]
 [1.   1.   1.   0.9  1.   1.   1.   0.45 0.65 1.  ]
 [1.   0.75 1.   1.   1.   1.   1.   1.   1.   0.25]
 [1.   1.   1.   1.   1.   1.   1.   0.95 1.   0.05]
 [1.   1.   1.   1.   1.   1.   0.95 1.   1.   0.05]
 [1.   1.   1.   1.   0.75 1.   1.   1.   1.   0.25]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]]


In [9]:
np.linalg.det(M)

3.9374999999999994e-07

In [10]:
M_1 = np.linalg.inv(M)

In [11]:
print(M_1)

[[  0.23809524   9.52380952  -7.04761905  -5.80952381   9.52380952
    3.80952381 -14.85714286   9.9047619    3.80952381  -8.08571429]
 [ -2.85714286   5.71428571  -5.42857143  -5.28571429   5.71428571
   -1.71428571  -1.71428571   1.14285714   2.28571429   2.02857143]
 [ -3.01587302  -3.96825397   3.43650794  -5.57936508   6.03174603
    2.41269841  -1.80952381  -2.12698413   2.41269841   2.08571429]
 [  4.52380952  -9.04761905   8.5952381   17.11904762 -19.04761905
   -3.61904762   7.71428571  -1.80952381  -3.61904762  -0.62857143]
 [ -2.85714286   5.71428571  -5.42857143  -5.28571429   5.71428571
    2.28571429  -1.71428571   1.14285714  -1.71428571   2.02857143]
 [ 12.06349206 -24.12698413  21.25396825  22.31746032 -24.12698413
   -9.65079365   7.23809524   8.50793651  -9.65079365  -3.34285714]
 [-18.0952381   36.19047619 -34.38095238 -33.47619048  36.19047619
   14.47619048 -10.85714286 -12.76190476  14.47619048   7.51428571]
 [-18.0952381   36.19047619 -34.38095238 -33.47619048  

In [12]:
res = M_1.dot(E)

In [13]:
print(res)

[[ 18.25431474]
 [ -1.00489931]
 [ -3.05627141]
 [ -6.98586655]
 [ -1.00489931]
 [ -7.25830282]
 [  8.46007774]
 [  8.46007774]
 [-15.11749309]
 [ -0.74673773]]
