In [1]:
import numpy as np

In [42]:
M = np.matrix(
    '0.04 0.24 0.24 0.24 0.24 0 0 0 0 0;' + 
    '0 0 0.1 0 0 0.55 0.35 0 0 0;'+
    '0 0 0 0 0 0.6 0.4 0 0 0;'+
    '0 0 0 0 0 0 0 0.6 0.4 0;'+
    '0 0 0 0.1 0 0 0 0.55 0.35 0;'+
    '0 0.25 0 0 0 0 0 0 0 0.75;' + 
    '0 0 0 0 0 0 0 0 0 1;' +
    '0 0 0 0 0 0 0.05 0 0 0.95;' +
    '0 0 0 0 0.25 0 0 0 0 0.75;'+
    '0 0 0 0 0 0 0 0 0 0'
)

In [43]:
from math import log2
E = []
for i in range(10):
    val = 0
    for j in range(10):
        if M[i,j] != 0:
            val += M[i,j] * log2(M[i,j])
    E.append([val])
    print(val)
E = np.matrix(E)

-2.162292189082415
-1.3366664819166874
-0.9709505944546686
-0.9709505944546686
-1.3366664819166874
-0.8112781244591328
0.0
-0.28639695711595625
-0.8112781244591328
0


In [44]:
M = np.ones((10,10)) - M
print(M)

[[0.96 0.76 0.76 0.76 0.76 1.   1.   1.   1.   1.  ]
 [1.   1.   0.9  1.   1.   0.45 0.65 1.   1.   1.  ]
 [1.   1.   1.   1.   1.   0.4  0.6  1.   1.   1.  ]
 [1.   1.   1.   1.   1.   1.   1.   0.4  0.6  1.  ]
 [1.   1.   1.   0.9  1.   1.   1.   0.45 0.65 1.  ]
 [1.   0.75 1.   1.   1.   1.   1.   1.   1.   0.25]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   0.  ]
 [1.   1.   1.   1.   1.   1.   0.95 1.   1.   0.05]
 [1.   1.   1.   1.   0.75 1.   1.   1.   1.   0.25]
 [1.   1.   1.   1.   1.   1.   1.   1.   1.   1.  ]]


In [45]:
np.linalg.det(M)

-2.2499999999999676e-07

In [46]:
M_1 = np.linalg.inv(M)

In [49]:
print(M_1)

[[ 2.50000000e+01 -4.00000000e+01  4.00000000e+01  4.00000000e+01
  -4.00000000e+01 -1.60000000e+01  2.60000000e+01 -3.34177130e-13
  -1.60000000e+01 -1.70000000e+01]
 [ 1.82684299e-14 -3.68594044e-14  1.24344979e-14  2.44002441e-14
  -3.45722477e-14 -4.00000000e+00  3.00000000e+00 -5.55111512e-15
  -7.72574801e-15  1.00000000e+00]
 [-4.82705663e-15 -1.00000000e+01  9.16666667e+00 -0.00000000e+00
   1.20676416e-14 -0.00000000e+00  3.16666667e+00 -3.33333333e+00
  -7.24058494e-15  1.00000000e+00]
 [-8.33333333e+00  1.66666667e+01 -1.58333333e+01 -6.66666667e+00
   6.66666667e+00  6.66666667e+00 -1.35000000e+01  3.33333333e+00
   6.66666667e+00  4.00000000e+00]
 [ 3.53302046e-14 -7.06604092e-14  5.71496873e-14  4.22118733e-14
  -7.06604092e-14 -1.95475261e-14  3.00000000e+00 -1.32307958e-14
  -4.00000000e+00  1.00000000e+00]
 [-2.60582990e-14  5.21165979e-14 -1.66666667e+00 -5.71301598e-14
   5.21165979e-14  1.00271238e-14 -1.26666667e+01  1.33333333e+01
   4.96098170e-14  1.00000000e+00

In [47]:
res = M_1.dot(E)

In [48]:
print(res)

[[ 1.16086625e+00]
 [ 3.24511250e+00]
 [ 5.42094089e+00]
 [-3.09509281e+00]
 [ 3.24511250e+00]
 [-2.20037510e+00]
 [ 5.72793914e+00]
 [ 3.18637597e+01]
 [-4.53682631e+01]
 [-1.06329690e-14]]
